name: Force CRLF for files inside the Git index

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  enforce-crlf:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce CRLF action
        uses: DecimalTurn/Enforce-CRLF@55065c78ddda1ca041e510168cc0424eb5801c5e  # v1.3.1
        with:
          extensions: .bas, .frm, .cls
          do-checkout: true
          fail-on-lf: true
