name: Force CRLF for files inside the Git index

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  enforce-crlf:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce CRLF action
        uses: DecimalTurn/Enforce-CRLF@0449d87338894e54eda4af44715428573450757a  # v1.3.0
        with:
          extensions: .bas, .frm, .cls
          do-checkout: true
          fail-on-lf: true
