name: Force CRLF for files inside the Git index

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  enforce-crlf:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce CRLF action
        uses: DecimalTurn/Enforce-CRLF@4de3b7c88e20b88ecaa0a9dbecb2a2a5c03c11be # v1.2.2
        with:
          extensions: .bas, .frm, .cls
          do-checkout: true
          do-push: true
